--liquibase formatted sql
--changeset alp:V1.0.0.0.1__create_eav_table.sql


CREATE TABLE DICOM_FILE_METADATA(
    METADATA_ID BIGINT NOT NULL,
    DATA_ELEMENT_CONCEPT_ID BIGINT,
    PERSON_ID BIGINT,
    VALUE_AS_NUMBER NUMERIC,
    VALUE_AS_CONCEPT_ID BIGINT,
    MEASUREMENT_SOURCE_VALUE NVARCHAR(50),
    METADATA_SOURCE_NAME NVARCHAR(255),
    METADATA_SOURCE_KEYWORD NVARCHAR(255),
    METADATA_SOURCE_TAG NVARCHAR(20) NOT NULL,
    METADATA_SOURCE_GROUP_NUMBER NVARCHAR(20),
    METADATA_SOURCE_VALUE_REPRESENTATION NVARCHAR(20),
    METADATA_SOURCE_VALUE_MULTIPLICITY NVARCHAR(20),
    METADATA_SOURCE_VALUE TEXT,
    IS_SEQUENCE BOOLEAN,
    SEQUENCE_LENGTH BIGINT,
    PARENT_SEQUENCE_ID BIGINT,
    IS_PRIVATE BOOLEAN,
    PRIVATE_CREATOR NVARCHAR(255),
    SOP_INSTANCE_ID NVARCHAR(255),
    INSTANCE_NUMBER BIGINT,
    IMAGE_OCCURRENCE_ID BIGINT NOT NULL,
    ETL_CREATED_DATETIME TIMESTAMP NOT NULL,
    ETL_MODIFIED_DATETIME TIMESTAMP NOT NULL
);

--rollback DROP TABLE DICOM_FILE_METADATA;