name: Docker Build and Push to Azure CR

on:
  workflow_dispatch:
    inputs:
      AZ_REGISTRY_REPOSITORY:
        type: string
        description: AZ_REGISTRY_REPOSITORY
        required: true
      DOCKER_IMG_TAG_NAME:
        type: string
        description: DOCKER_IMG_TAG_NAME
        required: true

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "🎉 The job was manually triggered by: ${{ github.actor }}"
      
      - name: Check out repository code
        uses: actions/checkout@v4
        with: 
          clean: false

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.AZ_REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.AZ_REGISTRY_USERNAME }}
          password: ${{ secrets.AZ_REGISTRY_PASSWORD }}
   
      - name: Build and push
        id: build-push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: "linux/amd64"
          tags: ${{ vars.AZ_REGISTRY_NAME }}.azurecr.io/${{ inputs.AZ_REGISTRY_REPOSITORY }}:${{ inputs.DOCKER_IMG_TAG_NAME }}
          context: .
          build-args: | 
            GIT_COMMIT_ARG=${{ github.sha }}

      - name: Output summary 
        run: | 
          echo "### Output summary 🚀" >> $GITHUB_STEP_SUMMARY
          echo "Job Status: ${{ job.status }} " >> $GITHUB_STEP_SUMMARY
          echo "AZ_REGISTRY_REPOSITORY: ${{ inputs.AZ_REGISTRY_REPOSITORY }} " >> $GITHUB_STEP_SUMMARY
          echo "DOCKER_IMG_TAG_NAME: ${{ inputs.DOCKER_IMG_TAG_NAME }} " >> $GITHUB_STEP_SUMMARY
          echo "GIT_COMMIT_ARG: ${{ github.sha }} " >> $GITHUB_STEP_SUMMARY
