name: build plugin

on:
  workflow_dispatch:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
  push:
    branches:
      - main
      - trex

env:
  GIT_CI_BRANCH_NAME: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@data2evidence'
      - name: Update version
        run: jq --arg v "-$(date +%s)-$GITHUB_SHA" '.version+=$v' package.json > tmppkg; mv tmppkg package.json
      - name: Publish
        run: |
           if [[ $GIT_CI_BRANCH_NAME == 'trex' || $GIT_CI_BRANCH_NAME == 'main' ]]; then 
              npm publish
           else 
              npm publish --dry-run
           fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v5
        with: 
          package-name: 'd2e-plugins'
          package-type: 'npm'
          min-versions-to-keep: 3
          delete-only-pre-release-versions: 'true'
      - name: Pack
        run: |
          if [[ $GIT_CI_BRANCH_NAME == 'main' ]]; then
            NPM_FILENAME=$(npm pack)
            echo "NPM_FILENAME=$NPM_FILENAME" >> $GITHUB_ENV
          fi
      - name: Push
        uses: svenstaro/upload-release-action@v2
        if: ${{ env.GIT_CI_BRANCH_NAME == 'main' }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.NPM_FILENAME }}
          tag: latest
          target_commit: main
          prerelease: true
          overwrite: true
          asset_name: d2e-plugins.tgz
      
